### ISSUE TITLE
Using datachannel-rs for native WebRTC clients

### ISSUE THREAD

**Issue by billyb2** [naia-rs/naia-socket#34]
What are your thoughts of using datachannel-rs for native WebRTC clients? I noticed that currently, you can only connect to a host if you're using WASM, and thought using datachannel-rs might be a good solution.

**Comment by naia-rs** [comment]
Hey billyb2, yeah I love it!

Native clients using WebRTC would be a huge upgrade to naia-socket, allowing a WebRTC server to handle connections from both native and web clients (meaning cross-play would be possible as well). The UDP transport layer currently used by native clients is super bare bones, and I would not recommend for production. Mostly because WebRTC has the advantage of more secure handshaking, encrypted communication via DTLS, and better connection management. So yeah, it has always been the plan to move native clients to WebRTC as well.

I've looked into datachannel-rs a bit, and yeah, I think it could work, but the effort to get it worked always looked somewhat monumental.. I've never used a dependency which is a binding to a C++ project .. I'm unsure if we'd be able to get the build process working smoothly enough that end-users of naia-socket don't have to change their build process too once we get it implemented? For that reason, I've personally been waiting for https://github.com/webrtc-rs/webrtc to get a native Rust solution working first before diving into this.

My other reason for waiting on this is that the native UDP implementation works well enough for my needs while developing my personal project (where the native build is necessary to simplify the debugging process - can't do that so easily on a Wasm-only project. But as my personal project gets closer to public deployment, I'll definitely want to spend some time hacking the native WebRTC portion in order to be able to deploy production-ready native builds.

If anyone wants to take a stab at creating an datachannel-rs example which connects to a naia-socket WebRTC server, pretty much ping-ponging back and forth like in the example, then I think it's very possible I'd be willing to spend the time hooking that up in the native client socket code. The biggest risk there is just over-complicating the build process, hopefully there would be a way past that hurdle.

Anyway, thanks for looking into this billyb!

**Comment by billyb2** [comment]
Of course, thank you for taking the time to respond! I've also been looking at webrtc-rs for the past few months, and I feel as though it will be a long time before it's working fully. I agree that it does complicate the build process somewhat, as it requires OpenSSL to be installed (which is the default and fairly easy for Linux as a whole, although I've heard it's a bit more difficult on Windows). I'd love to try to get datachannel-rs working with Naia, though I have a severe lack of understanding of how WebRTC works.

Thank you for responding!

**Comment by billyb2** [comment]
Hey, justa  quick update, how is the webrtc-rs library looking. I checked the Github lately, and it appears that the datachannel part is complete.

**Comment by naia-rs** [comment]
Hey billyb2, yeah thank you for the heads up! That is great news :) Very excited to dig into that, I've had a quick read around about the datachannel API & the examples.

I have a big refactor I want to get out within the next couple weeks (on both naia_socket & naia proper), and will likely hop onto figuring out how to get webrtc-rs into here soon after ... Also seems like it may be a good idea to let webrtc-rs bake just a bit longer since more people are likely trying it out now and will find bugs/issues.

If anyone else wants to take a shot at it in the meantime, that could help, thanks!

**Comment by billyb2** [comment]
I've actually been working on [adding native client support](https://github.com/naia-rs/naia-socket/pull/46) myself, though I could really use some help (WebRTC is confusing).

**Comment by naia-rs** [comment]
Thank you so much @billyb2 for giving it such a great shot! WebRTC is indeed confusing... Closing this to roll it into https://github.com/naia-rs/naia-socket/issues/56
