### ISSUE TITLE
Listening as both WebRTC and UDP server at once

### ISSUE THREAD

**Issue by RJ** [naia-rs/naia-socket#38]
Would be nice to be able to listen both on webrtc and UDP in the same server process, to support both types of client connecting at the same time.

Is there any technical reason preventing this, other than the need not arising yet? Any pointers on how to approach this?

Thanks

**Comment by naia-rs** [comment]
Definitely would be nice, thanks for looking into it.

There are 2 approaches:
1. Native WebRTC client - this is lightly referenced in https://github.com/naia-rs/naia-socket/issues/34 . Basically, we get rid of the UDP transport, and native clients can now talk to the WebRTC server using the same protocol as Wasm clients. I'd like to use native Rust to do this, so a prime candidate for this is https://webrtc.rs/ when it finishes (seems like there's some good progress there!)
2. Create a UDP listener (on a separate thread?) to take traffic from current native UDP clients, and mix in with messages received from WebRTC. You'll also need to attempt to keep track of whether a client that has connected to you has done so through UDP or WebRTC, and so when the server sends messages to a specific client, it will know which outgoing socket to send the message to.

So far, I've been hoping to follow plan #1 , because it would make the code a lot cleaner/simpler, wouldn't require tracking which protocol each client is using, as well as the fact that WebRTC is more production ready as a result of it's sophisticated handshake protocol & internal implementation of DTLS. The UDP implementation of naia-socket is vulnerable to a couple different kind of attacks, and is unencrypted.

Plan #2 is feasible though .. unfortunately I think that as soon as webrtc.rs is finished, I'd be in favor of reverting any changes made to get that working, in order to switch everything to just use WebRTC under the hood.

I'd be interested in your thoughts about this though! Hope that helps

**Comment by RJ** [comment]
I see, thanks for the explanation. I'd also much prefer native webrtc in rust and to ditch udp altogether, for the reasons you mentioned. It does look like webrtc.rs is making progress, so fingers crossed :)

I'll avoid thinking too hard about adding dual-listening for the time being and see how things pan out. 

Thanks for the great library!

**Comment by naia-rs** [comment]
Thank you RJ! Pulling this issue up into https://github.com/naia-rs/naia-socket/issues/56
