### ISSUE TITLE
WebRTC HTTPS support?

### ISSUE THREAD

**Issue by elijaharita** [naia-rs/naia-socket#51]
It seems like the session initiator endpoint is hardcoded to `"http://{}/{}"` in the WebRTC client.

Is there a way to use HTTPS at the moment, or is it still to-be-implemented?

EDIT - fyi, I am using nginx reverse proxy, so not looking for any sort of SSL support on the server itself. Just the ability to tell the client to connect over HTTPS.

**Comment by naia-rs** [comment]
I believe there's no way to use HTTPS at the moment but that's definitely going to the top of the to-do! Thanks for the heads up, this definitely needs another look :+1:

**Comment by elijaharita** [comment]
Oh great! I'm willing to contribute a PR for this if it would be helpful. I'd assume we could just add a field to `SocketConfig` and select between HTTP and HTTPS accordingly. (`rtc_use_https: bool`?)

Probably just a few lines change, but happy to do the work if needed

**Comment by naia-rs** [comment]
Thanks a lot for the offer @elijaharita , I definitely welcome the help!

Well I recently realized that I'm pretty sure that instead of a SocketAddr, `Client.connect(...)` needs to take a String or string-like value, which includes the URL's scheme, subdomain, second-level domain, top-level domain, and it'd be nice to use some type from `std` if it exists, I still need to look into that. Like it'd be nice if whatever that type is, it could validate that the string is correct and give some appropriate errors/hints if it gets constructed wrong. This is so we can do something like `Client.connect("https://webrtc.yourdomain.com")` in production ... but also be able to connect like `Client.connect("http://127.0.0.1:8888")` in a development environment

So that value would get passed in and you'd have `let server_url_str = format!("{}/{}", url, path);` at https://github.com/naia-rs/naia-socket/blob/8f0ce6c00467318f73509707ab8c8b8e8f573cee/client/src/impls/wasm_bindgen/webrtc_internal.rs#L50

Also it'd be a good time to make the DEFAULT_RTC_PATH at https://github.com/naia-rs/naia-socket/blob/8f0ce6c00467318f73509707ab8c8b8e8f573cee/shared/src/shared_config.rs#L5 something a little shorter/vague like `"webrtc"` maybe ..

**Comment by naia-rs** [comment]
just FYI @elijaharita , I'm working on fixing this now :+1:

**Comment by elijaharita** [comment]
Okay, nice!

For the type that should be passed into `connect()`, `url::Url` makes the most sense to me. But using that also for UDP connections feels strange since the full URL is totally unnecessary. What's your plan to differentiate between these two cases?

**Comment by elijaharita** [comment]
`&str` sounds good, that actually gives some more flexibility. You could still allow people who only plan to use UDP to specify only the address for simplicity, and just infer normal HTTP and the default endpoint path in that case. 

If you're going this route, could just allow specifying the URL path on the connect parameter itself, instead of ensuring that there is no path and then immediately appending a path based on the config option.

**Comment by naia-rs** [comment]
Fixed in https://github.com/naia-rs/naia-socket/releases/tag/v0.7.4, thank you!
