### ISSUE TITLE
Support async-std

### ISSUE THREAD

**Issue by msvbg** [naia-rs/naia-socket#9]
naia-socket is currently tied to the tokio runtime, which ties downstream consumers of the library to the tokio runtime. It may be worthwhile to support async-std as well, at some point down the line.

**Comment by naia-rs** [comment]
I'm so down for this! Does anyone have some good examples of libraries that support multiple runtimes? I'd like to see how that's set up. The reason that naia-socket is tied to tokio is because https://github.com/kyren/webrtc-unreliable is dependent on tokio - so that would be the place to start. I'm afraid I won't personally be able to focus on this for quite a while though

**Comment by msvbg** [comment]
Yep this is understandably low priority! I was considering doing this, but then I decided to just use tokio instead for now. I haven't researched how other libraries are dealing with this.

**Comment by smokku** [comment]
`naia-socket` works fine wrapped with [`async-compat`](https://crates.io/crates/async-compat).

**Comment by Miaourt** [comment]
Hello, seems that kyren dropped the hard requirement on tokio !
https://github.com/kyren/webrtc-unreliable/blob/master/CHANGELOG.md#05

**Comment by naia-rs** [comment]
Hey Miaourt, thanks for the heads up! Yes I did see this a bit ago and dropping the tokio requirement it will be part of next release, which will also include support for use of naia-socket in multi-threaded environments & moving off of wasm-bindgen (should increase performance & build times)

**Comment by naia-rs** [comment]
Resolved in Release 0.4.0: https://github.com/naia-rs/naia-socket/releases/tag/0.4.0
